name: Automatic conversion of application.yml to ors-config.yml
on:
  pull_request:
    branches:
      - main
      - releases/**
    types: [ opened, ready_for_review, reopened, synchronize ]
    paths:
      - 'ors-api/scr/main/resources/application.yml'
  workflow_dispatch:


jobs:
  detect_config_change:
    name: Detect and commit config changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Convert application.yml to ors-config.yml
        run: |
          .github/utils/config_conversion.sh ors-api/src/main/resources/application.yml ors-config.yml
      - uses: MichaelsJP/git-auto-commit-action@v5
        if: (! github.event.pull_request.draft) && github.event.pull_request.state == 'open'
        with:
          commit_message: 'chore(config): automatic conversion of application.yml to ors-config.yml'

